package main

import (
	
	"log"

	"github.com/serlip06/ws-serli2024/config"
	
	"github.com/aiteung/musik"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/serlip06/ws-serli2024/url"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "github.com/serlip06/ws-serli2024/docs"
	"github.com/gofiber/fiber/v2"
	
)

// @title TES SWAGGER ULBI
// @version 1.0
// @description This is a sample swagger for Fiber

// @contact.name API Support
// @contact.url https://github.com/serlip06
// @contact.email 714220023@std.ulbi.ac.id

// @host ws-serli2024-48bfd02e8f8c.herokuapp.com
// @BasePath /
// @schemes https http

func main() {
	site := fiber.New(config.Iteung)
	site.Use(cors.New(config.Cors))
	url.Web(site)
	log.Fatal(site.Listen(musik.Dangdut()))
}
