basePath: /
host: ws-serli2024-48bfd02e8f8c.herokuapp.com
info:
  contact:
    email: 714220023@std.ulbi.ac.id
    name: API Support
    url: https://github.com/serlip06
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
